### ISSUE TITLE
How to add DHL custom data to order totals

### ISSUE THREAD

**Issue by OvalMedia** [netresearch/module-shipping-ui#1]
I have a shop where orders, invoices, shipments and creditmemos are generated as PDF (Mageplaza Pdfinvoice module).
Additional DHL fees like "Wunschzustellung" don't show up in those order totals. The total sum ist correct but the individual order total items don't show up on the PDF.

The PDF generator simply takes the items from Magento\Sales\Block\Order\Totals::getTotals as expected.

How could I inject the custom totals from this module in there?

Thank you

**Comment by mam08ixo** [comment]
Thank you for reporting the issue. Missing custom total on PDFs turned out to be a regression in DHL Shipping v2.

Run `composer update --with-dependencies dhl/shipping-m2` to pull in the `netresearch/module-shipping-ui:2.0.2` dependency that fixes the issue for Magento sales PDFs.

Given that the 3rd party extension considers the totals defined for the native PDFs, then it should also work there.
